# Generated by Django 4.0 on 2022-01-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegatable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=255)),
                ('stock', models.IntegerField()),
                ('image_url', models.CharField(max_length=2800)),
            ],
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Fruits',
        ),
    ]
