# Generated by Django 4.0 on 2022-01-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_vegatable_rename_product_fruits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fruits',
            new_name='Fruit',
        ),
    ]
