# Generated by Django 4.0 on 2022-01-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_fruits_fruit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vegatable',
            new_name='Vegetable',
        ),
    ]
